version: 0.1.{build}
image: Visual Studio 2019

init:
  - git config --global core.autocrlf false

branches:
  only:
    - master
only_commits:
  files:
    - ZSpitz.Util/
    - ZSpitz.Util.Wpf/
    - appveyor.yml
skip_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- cmd: dotnet restore

artifacts:
  - path: '**\*.nupkg'
    type: NuGetPackage
  - path: '**\*.snupkg'
    type: NuGetPackage

deploy:
  - provider: NuGet
    api_key:
      secure: 76XN9J7Gg4Kkxt4XowKWEs8fzUQLXyJOKuPBVe455dWyXjOSMuWmueSWEPNeRAxy
    artifact: /.*(\.|\.s)nupkg/
